name: doc_care_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  doc_care_core:
    path: ../doc_care_core
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  googleapis_auth: ^1.6.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  rename: ^3.0.2
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/